name: 'Set Repository Description Action'
description: 'GitHub Action to set repository''s description.'
author: 'rtvu'

branding:
  icon: 'edit'
  color: 'gray-dark'

inputs:
  description:
    description: 'Description of repository'
    required: true
  repository:
    description: 'Name of repository with format <OWNER>/<REPOSITORY>'
    default: ${{ github.repository }}
  token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    -
      name: 'Set description'
      shell: bash
      run: gh repo edit ${{ inputs.repository }} --description "${{ inputs.description }}"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
