name: 'Set Tags'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  set-tags:
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Checkout repository'
        uses: actions/checkout@v4
      -
        name: 'Set tags'
        uses: rickstaa/action-update-semver@v1
